# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InjectionExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InjectionExample
  pod 'SnapKit', '~> 4.0.0'
  target 'InjectionExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InjectionExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
